[package]
name = "faktory"
version = "0.12.4"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

description = "API bindings for the language-agnostic Faktory work server"
repository = "https://github.com/jonhoo/faktory-rs.git"

keywords = ["faktory", "api-bindings", "work-server", "job-server"]
categories = ["api-bindings", "asynchronous", "network-programming"]

exclude = [".github", "docker", ".gitignore", "Makefile"]

[features]
default = []
tls = ["native-tls"]
binaries = ["clap"]
ent = []

[dependencies]
bufstream = "0.1"
chrono = { version = "0.4", features = ["serde", "clock"], default-features = false }
clap = { version = "4.4.10", optional = true }
derive_builder = "0.20.0"
fnv = "1.0.5"
hostname = "0.3"
libc = "0.2"
native-tls = { version = "0.2", optional = true }
rand = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.10.0"
thiserror = "1.0.30"
url = "2"

[dev-dependencies]
mockstream = "0.0.3"

# to make -Zminimal-versions work
[target.'cfg(any())'.dependencies]
openssl = { version = "0.10.60", optional = true }

[[bin]]
name = "loadtest"
path = "src/bin/loadtest.rs"
required-features = ["binaries"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
